### ISSUE TITLE
Trailing whitespace in CNF

### ISSUE THREAD

**Issue by kkalav** [aia-uclouvain/schlandals#2]
If a clause of a CNF-expression has a trailing whitespace after 0 the solver crashes with the rather mysterious error: 

```
thread 'main' panicked at /***/schlandals-0.1.3/src/parsers/mod.rs:78:83:
called `Option::unwrap()` on a `None` value
```

This could be avoided by trimming trailing whitespace, for example by adding 

`let line = line.trim_end()` 

to the parsing in cnf.rs

**Comment by AlexandreDubray** [comment]
Hey,
Thanks for the report! It should be fixed with commit 80694a3. If you experience any other issue with parsing CNF, feel free to re-open another issue!
